---

- name: Create .kube directory in user's home directory
  file:
    path: ~/.kube
    state: directory
    mode: 0755
  register: kube_home_dir
  ignore_errors: false

- name: Copy kubernetes admin.conf to ~/.kube
  shell: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  register: kube_conf
  when: kube_home_dir | succeeded
  ignore_errors: false

- name: Get pods status
  shell: kubectl get pods -n kube-system
  register: kube_system_pods
  when: kube_conf | succeeded
  ignore_errors: false
- debug:
    var: kube_system_pods.stdout
  when: kube_conf | succeeded
